Login screen
HauntedMilkshake/fitness_app pull request #16
Opened 2024-10-21 15:30 UTC by Gotalicp

- Remade ui of login screen in compose
- Fixed viewmodel for compose

2024-10-23 14:25 UTC, dimitarstoyanovtumba commented on app/src/main/java/bg/zahov/app/ui/authentication/AuthenticationState.kt
> +data class UiInfo(
Please add kdoc to all public classes and functions.

2024-10-23 14:27 UTC, dimitarstoyanovtumba commented on app/src/main/java/bg/zahov/app/ui/authentication/login/LoginFragment.kt
> +                LoginScreen(loginViewModel, findNavController())
The login screen itself doesn't need to hold control over the navController. Use a lambda as an argument callback instead and call the navigation function from this fragment.

2024-10-23 14:29 UTC, dimitarstoyanovtumba commented on app/src/main/java/bg/zahov/app/ui/authentication/login/LoginFragment.kt
> +        return ComposeView(requireContext()).apply {
requireContext and requireActivity can return a null or throw an exception. Use `context` instead.

2024-10-23 14:30 UTC, dimitarstoyanovtumba commented on app/src/main/java/bg/zahov/app/ui/authentication/login/LoginScreen.kt
> +            "Login",
Please extract all string resources.

2024-10-23 14:31 UTC, dimitarstoyanovtumba commented on app/src/main/java/bg/zahov/app/ui/authentication/login/LoginScreen.kt
> +            verticalArrangement = Arrangement.spacedBy(15.dp)
nit: As a good practice use paddings that are divisible by 4.

2024-10-23 14:32 UTC, dimitarstoyanovtumba commented on app/src/main/java/bg/zahov/app/ui/authentication/login/LoginViewModel.kt
> +    private val info: UiInfo = UiInfo()
Observable pattern with Kotlin Flow should be used here instead.

2024-10-23 14:35 UTC, dimitarstoyanovtumba commented on app/src/main/java/bg/zahov/app/ui/authentication/signup/SignupScreen.kt
> +//            CommonTextField(
Let's avoid committing commented code.

2024-10-23 14:35 UTC, dimitarstoyanovtumba commented on app/src/main/java/bg/zahov/app/ui/authentication/signup/SignupScreen.kt
> +fun showToast(message: String, context: Context) {
This function seems redundant.

2024-10-23 14:37 UTC, dimitarstoyanovtumba commented on app/src/main/java/bg/zahov/app/ui/custom/CommonPasswordField.kt
> +    @SuppressLint("ModifierParameter") modifier: Modifier = Modifier
Better to follow the lint rules than to suppress them.

2024-10-24 15:24 UTC, Gotalicp commented on app/src/main/java/bg/zahov/app/ui/authentication/login/LoginViewModel.kt
> +    private fun notifyChange(text: String? = null) {
waiting for Spas :)

2024-10-25 14:13 UTC, trifonov-i requested changes

2024-10-25 14:32 UTC, merged